apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
  creationTimestamp: null
  generation: 1
  labels:
    app: joker
  name: joker
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/joker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: joker
      name: joker
    spec:
      containers:
      - image: ocinbat/joker:ci-17
        imagePullPolicy: Always
        name: joker
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthcheck
            port: 80
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 30
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}